CREATE TABLE IF NOT EXISTS PEOPLE( 
	RUT 	  TEXT             NOT NULL,
	FIRSTNAME TEXT             NOT NULL,
	EMAIL     TEXT             NOT NULL,
	ADRESS    TEXT             NOT NULL
);

CREATE TABLE IF NOT EXISTS PERMISSIONS(
	ID SERIAL PRIMARY KEY,
	RUT 	 TEXT          NOT NULL,
	MOTIVO   TEXT          NOT NULL,
	DATE_EXT TIMESTAMP     NOT NULL,
	ADRESS   TEXT          NOT NULL
);